/*
 * COPYRIGHT (c) 2024-2026 INRAI / Mickaël Bourgeoisat / Emile Steiner
 * COPYRIGHT (c) 2017-2024 Mickaël Bourgeoisat / Emile Steiner
 * COPYRIGHT (c) 2009-2017 Mickaël Bourgeoisat
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the \"Software\"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modif_y, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 * 
 * Licence type : MIT.
 */

var h = h || {};
h.libs = h.libs || {};
/**
 * @class H_ajax
 * @classdesc
 * AJAX utility class for managing multiple concurrent AJAX requests, file uploads (including chunked uploads), 
 * progress tracking.<br><br>
 * Provides helpers for form serialization, file validation, and optionnaly TinyMCE image upload integration.<br>
 * We do not use javascript File API for a simple reason : we can't follow upload progress.<br>
 * Plus you can use async() await on succes or error if you need to do promisse like.<br>
 * This class is globaly instanciated as h.a but can be also found in h.libs.ajax.<br>
 * <br>
 * This class will use H_ajax_sender to create/manipulate the xhr object.<br>
 * And if there was some input files, formadata or blob sended, H.ajax_file will also be used.<br>
 * 
 * @example
 * basic usage :
 * automaticaly used by forms generated by helPHP server libs (h::form), you can create an ajax request like this:
 * ---------------------------------------------------------------
 *      let settings = {}; //our array of params 
 *      settings.url = ''; // the url to send you ajax request
 *      settings.data = { //the data key/pairs you want to send
 *          'param1':'value1' ,
 *          'param2':'value2' ,
 *          'param3':'value3',
 *          'action':'moduleaction'
 *          };
 *      settings.success = (res) => { //what to do with the result, set a callback etc...
 *          do something with res;
 *          };
 *      settings.error = (err) => { //what to do in case of error...
 *              do something with err;
 *              debugger;
 *          };
 *
 *      h.a.send(settings); //we send our request 
 *-----------------------------------------------------------------
 * @see https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications
 * @returns {Mixed} content depending module return
 */
class H_ajax {
    constructor() {
        this.xhr_list = [];
        this._up_loaded_bytes = 0;
        this._up_total_bytes = 0;

        this._down_loaded_bytes = 0;
        this._down_total_bytes = 0;

        // if the total size is unknow, these values will contains the upload/download bytes values
        this._up_overload = 0;
        this._down_overload = 0;

        this._up_speed = 0;
        this._down_speed = 0;

        this._consecutive_streams = 10; // how many simultaneous ajax streams are allowed at the same time
        this._busy_stream_count = 0;
        this._running_stream_count = 0;

        this._stream_queue = [];
        // different queue for sending chunk faster

        this._last_data_time = 0;

        this._debug = false;
    }

    /**
     * Converts all inputs in a form to a JSON object.
     * @function
     * @param {HTMLFormElement} form - The form element to serialize.
     * @returns {Object} The serialized form data as an object.
     */
    form_to_obj(form) {
        var obj = {};
        var elements = form.querySelectorAll( "input, select, textarea" );
        for( var i = 0; i < elements.length; ++i ) {
            let element = elements[i];
            let name = element.name;
            let value = element.value;
            let tag_type = element.type.toLowerCase();
            if( name ) {
                if( tag_type == "checkbox" || tag_type == "radio"){
                    if(element.checked){
                        obj[ name ] = value;
                    }

                }else {
                    obj[ name ] = value;
                }
            }
        }

        return obj;
    }
    /**
     * Submits a form when a select element changes.
     * 
     * @function
     * @param {HTMLElement} selectDomElement - The select element.
     * @returns {boolean} True if submitted, false otherwise.
     */
    static submit_on_change(selectDomElement){

        if(selectDomElement.form){
            selectDomElement.form._submitter = selectDomElement;
            H_event.send_event(selectDomElement.form , 'submit');
        }else{
            return false;
        }
        return true;
    }

    /**
     * Converts a raw byte size into a human-readable string.
     * @param {number} size - The size in bytes.
     * @returns {string} Human-readable file size.
     */
    readable_file_size(size){
        let cnt = 0;
        let units = ['bytes','KB','MB','GB','TB'];
        while(size > 1024 && cnt < units.length-1){
            size /= 1024;
            cnt ++;
        }
        return size.toFixed(2)+' '+units[cnt];
    }

    /**
     * Checks if the file inputs respect the server limitations.
     * @function
     * @param {HTMLElement|FormData} dom_element - The DOM element or FormData to check.
     * @returns {boolean} True if valid, false otherwise.
     */
    static check_file_data(dom_element){
        var lst = [];
        
        if(H_generics.is_formdata(dom_element)){
            if(dom_element.entries){
                let data = dom_element.entries();
                let obj = data.next();
                while(undefined !== obj.value) {
                    let t = Object.prototype.toString.apply(obj.value[1]);
                    if(t == '[object File]'){
                        lst.push(obj.value[1]);
                    }
                    obj = data.next();
                }
            }else{
                console.log('Formdata.entries not supported !');
            }

        }else if(H_generics.is_dom_object(dom_element)){
            
            if (dom_element.tagName == 'INPUT' && dom_element.type == 'file' && dom_element.files){
                // if the given dom element is a FILE input, get its files
                lst = dom_element.files;

            }else if(dom_element.tagName == 'FORM'){
                // if the given dom element is a FORM, get all the files from the FILE inputs inside this form
                let elements = dom_element.elements;

                for(let i = 0; i < elements.length ; i++){
                    if(elements[i].type == 'file'){
                        for(let f = 0; f < elements[i].files.length ; f++){
                            lst.push(elements[i].files[f]);
                        }
                    }
                }
            }
        }

        let count = lst.length;
        let size = 0;
        for(let i = 0; i < count ;i++){
            size += lst[i].size;
        }
        let message = '';
        if(count > H_ajax.max_file_uploads){
            message += H_constants.get_text('too_many_files' , [count,H_ajax.max_file_uploads]); //'Too many files ('+count+')! Max = '+H_ajax.max_file_uploads;
        }
        if(size > H_ajax.max_upload_size){
            message += H_constants.get_text('too_heavy_files' , [H_ajax.readable_file_size(size),H_ajax.readable_file_size(H_ajax.max_upload_size)] ); //'Files are too heavy ('+H_ajax.readable_file_size(size)+')! Max = '+H_ajax.readable_file_size(H_ajax.max_upload_size);
        }

        if(message !== ''){
            H_ui.message_popup(message);
            return false;
        }else{
            return true;
        }
    }
    
    /**
     * TinyMCE image upload handler for AJAX image uploads.
     * called by Tinymce.php lib optionnaly
     * @function 
     * @param {Object} blobInfo - TinyMCE blobInfo object.
     * @param {Function} success - Success callback.
     * @param {Function} failure - Failure callback.
     */
    static tinymce_image_upload_handler(blobInfo, success, failure) {
        var xhr, formData;

        xhr = new XMLHttpRequest();
        xhr.withCredentials = false;
        xhr.open('POST', this.url);

        xhr.onload = function() {
            let json;

            if (xhr.status != 200) {
                failure('HTTP Error: ' + xhr.status);
                return;
            }

            try{
                json = JSON.parse(xhr.responseText);
            }catch(e){
                json = false;
                console.log(e);
            }

            if (!json || typeof json.location != 'string') {
                failure('Invalid JSON: ' + xhr.responseText);
                return;
            }

            success(json.location);
        };

        formData = new FormData();
        formData.append('file', blobInfo.blob(), blobInfo.filename());
        formData.set('action', this.action);

        console.log(blobInfo.filename());

        xhr.send(formData);
    }
    /**
     * Sleep utility function (async).
     * can be used to async / wait, 
     * @function
     * @param {number} ms - Milliseconds to sleep.
     * @returns {Promise<void>} Promise that resolves after the delay.
     * @example
     * await h.a.sleep(5000);
     * or
     * await H_anim.sleep(5000);
     */
    static sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }
    /**
     * Gets the first available XHR sender or creates a new one.
     * @returns {H_ajax_sender} The sender instance.
     */
    get_sender(){

        let sender = null;

        for(let i = 0 , c = this.xhr_list.length; i < c ; i++){
            if(!this.xhr_list[i].busy){
                if(this._debug){
                    console.log('reuse sender ',i);
                }
                sender = this.xhr_list[i];
                break;
            }
        }

        if(sender === null){
            if(this._debug){
                console.log('create sender');
            }
            sender = new H_ajax_sender();
            this.xhr_list.push(sender);
        }

        sender._debug = this._debug;
        sender.ignore_file = false;

        return sender;
    }

    /**
     * Sends data according to the provided settings.
     * @param {Object} settings - AJAX settings.
     * @param {number} delay - Optional delay before sending.
     * @param {boolean} queue - Whether to queue the request.
     * @returns {H_ajax_sender|boolean} The sender or false if queued.
     */
    send(settings , delay , queue){

        let sender = this.get_sender();

        sender._debug = this._debug;

        if(this.running_stream_count <= this._consecutive_streams && !delay && !queue){
            sender.send(settings);
            return sender;
        }else{
            // if too many ajax stream are running, put the current in a waiting queue and run it later
            if(sender.set_data(settings)){
                if(delay){
                    sender._delayedSendTime = Date.now() + delay;
                }

                this.queue(sender);
            }
            return false;
        }
    }
    /**
     * Queues a sender for later execution.
     * @param {H_ajax_sender} sender - The sender to queue.
     */
    queue(sender){

        this._stream_queue.push(sender);

        if(!H_generics.is_function(sender)){
            sender._state = H_ajax_sender.STATE_QUEUED;
        }

        // try again to run the ajax call in 200ms
        if(this._queue_timer){
            clearTimeout(this._queue_timer);
        }

        this._queue_timer = setTimeout(this._process_queue.bind(this),200);
    }
    /**
     * Processes the AJAX queue.
     * @private
     */
    _process_queue(){

        if(this._queue_timer){
            clearTimeout(this._queue_timer);
        }

        // try to run the next ajax stream
        if(this._stream_queue.length){

            if(H_generics.is_function (this._stream_queue[0])){
                let f = this._stream_queue.shift();
                f();
            }else{

                if(this.running_stream_count <= this._consecutive_streams){

                        let sender = this._stream_queue[0];
                        let send = false;
                        if(sender._delayedSendTime){
                            if(Date.now() >= sender._delayedSendTime){
                                send = true;
                            }
                        }else{
                            send = true;
                        }
                        // test for the big file upload pause
                        if (sender._file && sender.pause_on_next_chunk){
                            send = false;
                        }
                        if(send){
                            sender = this._stream_queue.shift();
                            sender.send();
                        }

                }
            }
            this._queue_timer = setTimeout(this._process_queue.bind(this),200);
        }
    }

    /**
     * Computes the global progress for all running AJAX streams.
     */
    compute_progress() {
        let up_bytes_loaded = 0;
        let up_bytes_total = 0;

        let down_bytes_loaded = 0;
        let down_bytes_total = 0;

        let up_unknown_loaded = 0;
        let down_unknown_loaded = 0;

        this._up_overload = 0;
        this._up_speed = 0;
        this._down_speed = 0;
        this._speed = 0;

        this._down_zero_loaded = 0;
        this._down_zero_total = 0;

        for(let i = 0 , c = this.xhr_list.length; i < c ; i++){
            let x = this.xhr_list[i];
            if(x.busy){
                this._up_speed += x.up_speed;
                this._down_speed += x.down_speed;

                if(x._state == H_ajax_sender.STATE_UPLOADING){
                    this._speed += x.up_speed;
                }

                if(x._state == H_ajax_sender.STATE_DOWNLOADING){
                    this._speed += x.down_speed;
                }

                if(x.up_progress === null){
                    up_unknown_loaded += x.up_loaded_bytes;
                }else{
                    up_bytes_loaded += x.up_loaded_bytes;
                    up_bytes_total += x.up_total_bytes;
                }

                if(x.down_progress === null){
                    down_unknown_loaded += x.down_loaded_bytes;
                }else{
                    down_bytes_loaded += x.down_loaded_bytes;
                    down_bytes_total += x.down_total_bytes;

                    if(x._download_done && x.down_total_bytes === 0){
                        this._down_zero_loaded ++;
                        this._down_zero_total ++;
                    }
                }


            }
        }

        if(up_unknown_loaded + up_bytes_loaded > up_bytes_total){
            up_bytes_total = up_unknown_loaded + up_bytes_loaded;
            this._up_overload = up_unknown_loaded;
        }

        if(down_unknown_loaded + down_bytes_loaded > down_bytes_total){
            down_bytes_total = down_unknown_loaded + down_bytes_loaded;
            down_bytes_loaded += down_unknown_loaded;
            this._down_overload = down_unknown_loaded;
        }

        this._down_loaded_bytes = down_bytes_loaded;
        this._down_total_bytes = down_bytes_total;

        this._up_loaded_bytes = up_bytes_loaded;
        this._up_total_bytes = up_bytes_total;

        this._last_data_time = Date.now();
    }

    // indicates a temporary upload info until we had a correct update from the browser
    get up_overload(){
        return this._up_overload;
    }

    // indicates a temporary dowload info until we had an answer from the server
    get down_overload(){
        return this._down_overload;
    }

    // current overall upload speed
    get up_speed(){
        return this._up_speed;
    }

    // current overall download speed
    get down_speed(){
        return this._down_speed;   
    }

    // number of XHR doing something (initialization, upload, download, finalization ...)
    get busy_stream_count(){
        this._busy_stream_count = 0;
        for(let i = 0 , c = this.xhr_list.length; i < c ; i++){
            if(this.xhr_list[i].busy){
                this._busy_stream_count++;
            }
        }
        return this._busy_stream_count;
    }

    // number of transfer in progress
    get running_stream_count(){
        this._running_stream_count = 0;
        for(let i = 0 , c = this.xhr_list.length; i < c ; i++){
            if(this.xhr_list[i].running){
                this._running_stream_count++;
            }
        }
        return this._running_stream_count;
    }

    // overall upload progress (value between 0 and 1)
    get up_progress(){
        if(this._last_data_time === 0 || (Date.now() - this._last_data_time) > 100){
            this.compute_progress();
        }
        return this._up_total_bytes > 0 ? this._up_loaded_bytes / this._up_total_bytes : 0;
    }

    // overall download progress (value between 0 and 1)
    get down_progress(){
        if(this._last_data_time === 0 || (Date.now() - this._last_data_time) > 100){
            this.compute_progress();
        }
        return this._down_total_bytes > 0 ? this._down_loaded_bytes / this._down_total_bytes : this._down_zero_total > 0 ? this._down_zero_loaded / this._down_zero_total : 0;
    }

    // overall progression average
    get progress(){
        return (this.up_progress + this.down_progress) * 0.5;
    }

    // overall speed average
    get speed(){
        return this._speed;
    }
}

// these two variables have to be update by PHP script to reflect server the configuration
H_ajax.max_upload_size = h_storage.max_upload_size; // max file upload size
H_ajax.max_file_uploads = h_storage.max_file_uploads; // max number of simultaneous file uploads

// variable used in conjunction with the PHP H_ajax to identify json variables
H_ajax.json_list_identifier = H_constants.json_list_identifier; //'_AJAX_json_decode_list';

H_ajax.JSON_OFF = 0; // json data stay as strings
H_ajax.JSON_ON = 1; // json data are converted to objetcs and arrays
H_ajax.JSON_ARRAY = 2; // json data are converted, and objects are converted to associative arrays

h.libs.ajax = H_ajax;
window.H_ajax = H_ajax;

//****************************************************************************************
/**
 * @class H_ajax_sender
 * @classdesc
 * Handles a single AJAX request, including upload/download progress, callbacks, 
 * and response processing. Used internally by H_ajax.
 */
class H_ajax_sender {
    constructor(){
        this._xhr = new XMLHttpRequest();

        this._xhr._H_ajax_sender = this;
        this._xhr.upload._H_ajax_sender = this;

        this._xhr.addEventListener('loadend',this.on_download_end.bind(this));
        this._xhr.addEventListener('progress',this.on_down_progress.bind(this));

        this._xhr.addEventListener('load' , this.process_response.bind(this));
        this._xhr.addEventListener('error' , this.process_response.bind(this));

        this._xhr.upload.addEventListener('loadend',this.on_upload_end.bind(this));
        this._xhr.upload.addEventListener('progress',this.on_up_progress.bind(this));

        this._xhr.addEventListener('readystatechange' , this.ready_state_change.bind(this));

        this._state = H_ajax_sender.STATE_NOTHING;

        this.reset();
    }

    /**
     * Handles ready state changes of the XHR.
     * @param {Event} event - The event object.
     */
    ready_state_change(event){

        switch(this.readyState){
            case this.UNSENT:
                if(this._debug){ console.log('init',event); }
            break;

            case this.OPENED:
                if(this._debug){ console.log('connection open',event); }
            break;

            case this.HEADERS_RECEIVED:
                if(this._debug){
                    console.log('header received',event);
                    console.log(this.getAllResponseHeaders());
                }
            break;

            case this.LOADING:
                if(this._debug){ console.log('loading ...',event); }
            break;

            case this.DONE:
                if(this._debug){ console.log('all done',event); }
                
            break;

        }

    }
    /**
     * Resets the sender state.
     */
    reset(){

        this._data = null;
        this._localdata = null;

        this._busy = false;
        this._action = '';
        this._method = 'POST';

        this._state = H_ajax_sender.STATE_NOTHING;

        this._up_progress = 0;
        this._down_progress = 0;

        this._up_total_bytes = 0;
        this._down_total_bytes = 0;

        this._up_loaded_bytes = 0;
        this._down_loaded_bytes = 0;

        this._current_success_callback = null;
        this._current_error_callback = null;
        this._current_down_progress_callback = null;
        this._current_up_progress_callback = null;

        this._last_up_time = 0;
        this._last_down_time = 0;

        this._up_speed = 0;
        this._down_speed = 0;

        this._download_done = false;

    }

    /**
     * Handles upload progress events.
     * @param {ProgressEvent} event - The progress event.
     */
    on_up_progress(event){

        //let target = this._H_ajax_sender || this;
        let target = this;

        target._state = H_ajax_sender.STATE_UPLOADING;

        if(target._last_up_time > 0 && event.loaded != event.total){
            let time_offset = Date.now() - target._last_up_time;
            let bytes_offset = event.loaded - target._up_loaded_bytes;

            target._up_speed = bytes_offset * (1000 / time_offset);
        }
        target._last_up_time = Date.now();

        if(target._send_time <= 0){
            target._send_time = target._last_up_time;
        }

        target._up_loaded_bytes = event.loaded;

        if (event.lengthComputable) {
            target._up_progress = event.loaded / event.total;
            target._up_total_bytes = event.total;
        }else{
            target._up_progress = null;
            target._up_total_bytes = null;
        }


        if(this._current_up_progress_callback){
            this._current_up_progress_callback(event,this);
        }
    }

    /**
     * Handles download progress events.
     * @param {ProgressEvent} event - The progress event.
     */
    on_down_progress(event){

        let target = this;
        target._state = H_ajax_sender.STATE_DOWNLOADING;

        if(target._last_down_time > 0 && event.loaded != event.total){
            let time_offset = Date.now() - target._last_down_time;
            let bytes_offset = event.loaded - target._down_loaded_bytes;
            target._down_speed = bytes_offset * (1000 / time_offset);
        }
        target._last_down_time = Date.now();

        if(target._send_time <= 0){
            target._send_time = target._last_down_time;
        }

        target._down_loaded_bytes = event.loaded;

        if (event.lengthComputable) {

            target._down_progress = event.loaded / event.total;
            target._down_total_bytes = event.total;
        }else{
            target._down_progress = null;
            target._down_total_bytes = null;
        }

        if(this._current_down_progress_callback){
            this._current_down_progress_callback(event,this);
        }
    }
    /**
     * Sets data and configuration for the AJAX request.
     * @param {Object} settings - AJAX settings. possible values :<br>
     *      - action = url php script<br>
     *      - data = form dom object, formdata object, or and object with variables to send<br>
     *      - extra_data = object with additional variables to send<br>
     *      - down_progress : progress callback for download<br>
     *      - up_progress : progress callback for upload<br>
     *      - error : error callback<br>
     *      - success : success callback<br>
     *      - json_mode:<br>
     *      -     H_ajax.JSON_OFF = 0 = the json string untouched server side<br>
     *      -     H_ajax.JSON_ON = 1 = basic json decode server side : js objects are converted to PHP objects and js arrays to PHP arrays<br>
     *      -     H_ajax.JSON_ARRAY = 2 = (default) automatically convert json strings to PHP associative arrays when an object or an array is sent<br>
     *
     * @returns {boolean} True if data is set, false otherwise.
     */
    set_data(settings){
        settings = settings || {};

        if(settings['skip_container']){
            delete(settings['skip_container']);
            if(!settings.extra_data) settings.extra_data = {};
            settings.extra_data[H_constants.posted_varname] = 1;
        }


        this.reset();
        
        this._timer_needed = (settings.no_timer == undefined);

        let formAction = null;

        if(H_generics.is_object(settings) && settings.tagName == 'FORM'){
            formAction = settings.getAttribute('action');
        }

        if(!settings.action && settings.url){
            settings.action = settings.url;
        }

        settings.action = settings.action || this._action;
        settings.method = settings.method || this._method;

        if(settings.json_mode === undefined){
            settings.json_mode = H_ajax.JSON_ARRAY;
        }

        // local data retrievable on receipt of the query result, in the sender object
        if(settings.localdata !== undefined){
            this._localdata = settings.localdata;
        }

        let json_decode_list = [];
        let json_list_identifier = H_ajax.json_list_identifier;
        
        this._fileLst = [];
        
        if(H_generics.is_object(settings.data)){

            if(H_generics.is_formdata(settings.data)){

                let already_parsed = [];
                let toReplace = [];
                for (var pair of settings.data.entries()){
                    if (already_parsed.indexOf(pair[0]) == -1){
                        let vals = settings.data.getAll(pair[0]);
                        let is_file = false;
                        let newVal = [];
                        //~ console.log(pair);
                        
                        vals.forEach((val,key)=>{
                            if (!H_generics.is_string(val)){
                                // a value in formData can be a string or a file
                                this._fileLst.push({
                                    dom_id: false,
                                    data: val
                                });
                                newVal.push(val.name);
                                is_file = true;
                            }
                        });
                        if (is_file){
                            already_parsed.push(pair[0]);
                            toReplace.push({'key': pair[0], 'val':newVal});
                        }
                        already_parsed.push(pair[0]);
                    }
                }
                // toReplace.forEach((obj)=>{settings.data.set(obj.key, obj.val);});
                toReplace.forEach((obj)=>{settings.data.delete(obj.key);});

            }else if(settings.data.tagName === 'FORM'){
                // add form inputs
                settings.action = settings.action || settings.data.getAttribute('action');
                settings.method = settings.method || settings.data.getAttribute('method');

                let only_submitter = false;
                if(settings.data._submitter){
                    if(!settings.extra_data){
                        settings.extra_data = {};
                    }
                    settings.extra_data[settings.data._submitter.name] = settings.data._submitter.value;
                    if(settings.data._submitter.getAttribute('data-only')){
                        only_submitter = true;
                    }
                }

                let formData;
                if(only_submitter){
                    formData = new FormData();
                }else{

                    formData = new FormData();

                    let el = settings.data.elements;
                    for(let i = 0; i < el.length ; i++){
                        let input = el[i];
                        let tag_name = input.tagName.toLowerCase();
                        let tag_type = input.type.toLowerCase();

                        if(tag_name == "button" && tag_type == "submit" && settings.data._submitter && settings.data._submitter !== input){
                            // we exclude submits that are not used
                            continue;
                        }
                        if (tag_name == 'fieldset' || tag_name == 'button'){
                            // exclude elements that got no data
                            continue;
                        }

                        if(tag_name == "input" && tag_type == "file"){
                            if (this.ignore_file){
                                continue;
                            }
                            for(let f=0; f < input.files.length ; f++){
                                this._fileLst.push({
                                    dom_id: input.dataset.dom_id,
                                    data: input.files[f]
                                });
                                formData.append( input.name , input.files[f].name);
                                
                            }
                        }else{
                            if(tag_name == "input" && tag_type == "checkbox"){
                                if(input.checked){
                                    formData.append( input.name , input.value);
                                }

                            }else if(tag_name == "input" && tag_type == "radio"){
                                if(input.checked){
                                    formData.append( input.name , input.value);
                                }
                            }else{
                                formData.append( input.name , input.value);
                            }
                        }

                    }


                }

                settings.data = formData;

            }else{
                // add object data
                let formData = new FormData();

                let keys = Object.keys(settings.data);

                for(let i = 0 , c = keys.length; i < c ; i++){

                    let name = keys[i];
                    let value = settings.data[name];

                    if(value === true){
                        value = 1;
                    }

                    if(value === false){
                        value = 0;
                    }

                    if(H_generics.is_object(value)){
                        if (H_generics.is_file_list(value)){
                            for(let i=0; i<value.length; i++){
                                this._fileLst.push({
                                    dom_id: false,
                                    data: value[i]
                                });
                                formData.append( name , value[i].name);
                            }
                        } else if (H_generics.is_file(value)){
                            this._fileLst.push({
                                dom_id: false,
                                data: value
                            });
                            formData.append( name , value.name);
                        } else {
                            formData.append( name , JSON.stringify(value));
                            if(settings.json_mode){
                                json_decode_list.push(name);
                            }
                        }
                    }else{
                        formData.append( name, value );
                    }
                }
                settings.data = formData;
            }
            if(!H_ajax.check_file_data(settings.data)){
                return;
            }

            // add extra data
            if(H_generics.is_object(settings.extra_data)){

                let keys = Object.keys(settings.extra_data);

                for(let i = 0 , c = keys.length; i < c ; i++){

                    let name = keys[i];
                    let value = settings.extra_data[name];

                    if(H_generics.is_object(value) ){
                        settings.data.append( name , JSON.stringify(value) );
                        if(settings.json_mode){
                            json_decode_list.push( name );
                        }
                    }else{
                        settings.data.append( name , value );
                    }
                }
            }

            if(settings.json_mode){
                settings.data.append(json_list_identifier , JSON.stringify(json_decode_list));
                settings.data.append(json_list_identifier+'_mode' , settings.json_mode);
            }
        }
        if(settings.debug){
            console.log(this);
            for(var pair of settings.data.entries()) {
            console.log(pair[0] ,'=', pair[1]);
            }
        }

        if(H_generics.is_function(settings.success)){
            this._current_success_callback = settings.success;
        }else{
            this._current_success_callback = null;
        }

        if(H_generics.is_function(settings.error)){
            this._current_error_callback = settings.error;
        }else{
            this._current_error_callback = null;
        }

        if(H_generics.is_function(settings.up_progress)){
            this._current_up_progress_callback = settings.up_progress;
        }else{
            this._current_up_progress_callback = null;
        }

        if(H_generics.is_function(settings.down_progress)){
            this._current_down_progress_callback = settings.down_progress;
        }else{
            this._current_down_progress_callback = null;
        }

        this.busy = true;
        this._method = settings.method;
        this._action = formAction || settings.action;
        this._dom_target = H_dom.get_dom_element(settings.dom_target);
        this._replace_dom_target = settings.replace_dom_target;
        this._allow_target_update = settings.disable_target_update ? false : true;
        this._data = settings.data;
        return true;
    }

    get dom_target(){
        return this._dom_target;
    }
    
    get data(){
        return this._data;
    }

    get method(){
        return this._method;
    }

    get action(){
        return this._action;
    }

    /**
     * Updates response data after a download.
     * @param {ProgressEvent} event - The progress event.
     */
    update_response_data(event){
        this._down_total_bytes = event.total;
        this._down_loaded_bytes = event.loaded;

        this._download_done = true;

        // compute the average download speed
        if(this._send_time > 0){
            this._down_speed = event.loaded * (1000 / (Date.now() - this._send_time));
        }

        if(this._current_down_progress_callback !== null){

            // execute the progress call back for a last update
            this._current_down_progress_callback(event , this);

        }
    }

    /**
     * Processes JSON responses and handles UI feedback.
     * @param {Object|string} result - The AJAX result.
     */
    static process_json(result){
        if(H_generics.is_object(result)){

            if(result.reload_after_message){
                result.url = result.reload_after_message;
            }

            if(result.messages){
                H_ui.message_popup(result.messages , result.reload_after_message ? H_dom.reload_page.bind(result) : undefined );
            }

            if(result.url === H_constants.reload_noparams){
                H_dom.reload_page(result.url);
            }else{
                if(result.errors){
                    H_ui.message_popup(result.errors , result.reload_after_message ? H_dom.reload_page.bind(result) : undefined );
                }
            }
        }
    }

    /**
     * Processes the AJAX response.
     * @param {Event} event - The event object.
     */
    process_response(event){

        let type = this._xhr.getResponseHeader('Content-Type');

        //hide waiting modal
        if (!h.timer_modal_hidden && h.timer_modal){
            h.timer_modal.hide();
            h.timer_modal_hidden = true;
        }

        let result = this._xhr.responseText;
        if(type == 'application/json'){
            try{
                result = JSON.parse(result);
            }catch(e){
                result = this._xhr.responseText;
            }
        }

        this.update_response_data(event);

        if(this._xhr.status >= 400){
            console.error('Ajax Error',this._xhr);
            if(this._current_error_callback){
                this._current_error_callback(result , this);
            }

        }else{

            H_ajax_sender.process_json(result);

            if(this._dom_target && this._allow_target_update){

                if(H_generics.is_object(result)){

                    if(result.html !== undefined){
                        if(this._replace_dom_target){
                            H_dom.replace_element(this._dom_target , result.html);
                        }else{
                            H_dom.write_html(this._dom_target , result.html );
                        }

                    }

                }else if(H_generics.is_string(result)){
                    if(this._replace_dom_target){
                        H_dom.replace_element(this._dom_target , result);
                    }else{
                        H_dom.write_html(this._dom_target , result );
                    }
                }else{
                    console.warn('Wrong ajax result type',result);
                }
            }

            if(this._current_success_callback){
                this._current_success_callback(result , this);
            }
        }
    }
    /**
     * Processes AJAX errors.
     * @param {Event} event - The event object.
     */
    process_error(event,...args){
        console.log(event);
        console.log(this._xhr);
        console.log(args);

        let type = this._xhr.getResponseHeader('Content-Type');
        
        //hide waiting modal
        if (!h.timer_modal_hidden && h.timer_modal){
            h.timer_modal.hide();
            h.timer_modal_hidden = true;
        }

        let result = this._xhr.responseText;
        if(type=='application/json'){
            result = JSON.parse(result);
        }

        this.update_response_data(event);

        if(this._current_error_callback){
            this._current_error_callback(result , this);
        }

        if(this._dom_target && this._allow_target_update){

            if(H_generics.is_object(result)){

                if(result.html !== undefined){
                    H_dom.write_html(this._dom_target , result.html );
                }

            }else if(H_generics.is_string(result)){
                H_dom.write_html(this._dom_target , result );

            }else{
                console.warn('Wrong ajax result type',result);
            }
        }

    }
    /**
     * Sends the AJAX request.
     * @param {Object} [settings] - Optional AJAX settings.
     * @returns {boolean|undefined} False if not sent.
     */
    send(settings){
        // when sending a file, need to save the settings object before the processing
        let originalSettings = settings;
        
        if(settings){
            if(!this.set_data(settings)){
                return false;
            }
        }

        // detect if there is a media shared in the data to ask for what to do with it
        // before uploading
        if (this.data.has('media_is_shared') && parseInt(this.data.get('media_is_shared')) == 1 && this.data.has('media_modified') && parseInt(this.data.get('media_modified')) == 1){
            // debugger;
            // if (this.data.has('media_data[' + this.data.has))
            let b1 = {
                'label': H_constants.get_text('media_replace_all'),
                'handler': ()=>{Media_a.resend_after_choice(this, true);},
            };
            let b2  = {
                'label': H_constants.get_text('media_replace_one'),
                'handler': ()=>{Media_a.resend_after_choice(this, false);},
            };
            let setts = {
                'contentClass': 'media_is_shared',
                'content': H_constants.get_text('media_prompt_is_shared'),
                'buttons': [b1, b2]
            };
            let prompt = new H_ui_prompt(setts);
            prompt.set_parent(document.body, 0.5, 0.5);
            // console.log(prompt);
            return;
        }
        
        if (this._fileLst.length > 0){
            this.ignore_file = true;
            // console.log(this._fileLst);
            let fileSender = new H_ajax_file(this._fileLst,this);
            return;
        }

        
        

        this._xhr.open(this._method, this._action , true);
        
        this._xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
        this._xhr.setRequestHeader('Cache-Control', 'no-cache');
        
        if (this._xhr.readyState != 1) {
            console.warn("Cannot send this request because the XMLHttpRequest.readyState is not OPENED.");
            console.log(this);
            return;
        }

        if (h.timer_modal_hidden && this._timer_needed) {
            h.timer_modal.show();
            h.timer_modal_hidden = false;
        }

        this._xhr.send(this._data);
        this.running = true;

        this._state = H_ajax_sender.STATE_UPLOADING;

        this._send_time = Date.now();
    }
    /**
     * Aborts the AJAX request.
     * @param {Event} [event] - Optional event.
     */
    abort(event){
        this._current_success_callback = null;
        this._current_error_callback = null;
        this._current_down_progress_callback = null;

        this.busy = false;
        this.running = false;

        this._xhr.abort();
    }
    /**
     * Handles the end of a download.
     * @param {Event} event - The event object.
     */
    on_download_end(event){

        let H_ajax_sender = this;
        let xhr = H_ajax_sender._xhr;

        if(H_ajax_sender._debug){
            console.log('DOWN end',event);
        }

        // compute the average download speed
        if(H_ajax_sender._send_time > 0){
            H_ajax_sender._down_speed = event.loaded * (1000 / (Date.now() - H_ajax_sender._send_time));
        }

        if(H_ajax_sender._current_down_progress_callback){

            // execute the progress call back for a last update
            H_ajax_sender._current_down_progress_callback(event , this);

        }

        H_ajax_sender._current_success_callback = null;
        H_ajax_sender._current_error_callback = null;
        H_ajax_sender._current_down_progress_callback = null;

        H_ajax_sender.busy = false;
        H_ajax_sender.running = false;

        xhr.abort();

    }
    /**
     * Handles the end of an upload.
     * @param {Event} event - The event object.
     */
    on_upload_end(event){

        let H_ajax_sender = this;
        let xhr = H_ajax_sender._xhr;

        if(this._debug){
            console.log('UP end',event);
        }

        H_ajax_sender._up_total_bytes = event.total;
        H_ajax_sender._up_loaded_bytes = event.loaded;

        // compute the average upload speed
        if(H_ajax_sender._send_time > 0){
            H_ajax_sender._up_speed = event.loaded * (1000 / (Date.now() - H_ajax_sender._send_time));
        }

        if(H_ajax_sender._current_up_progress_callback){

            // execute the progress call back for a last update
            H_ajax_sender._current_up_progress_callback(event,this);

        }

        H_ajax_sender._current_up_progress_callback = null;

        // reset time counter for the download step coming after this
        H_ajax_sender._send_time = Date.now();
    }

    get busy(){
        return this._busy;
    }
    set busy(value) {
        this._busy = value === true;
    }
    

    get progress(){
        if(this._up_progress === null || this._down_progress === null){
            return null;
        }
        return (this._up_progress + this._down_progress) * 0.5;
    }

    get up_progress(){
        return this._up_progress;
    }

    get down_progress(){
        return this._down_progress;
    }

    get up_loaded_bytes(){
        return this._up_loaded_bytes;
    }

    get up_total_bytes(){
        return this._up_total_bytes;
    }

    get down_loaded_bytes(){
        return this._down_loaded_bytes;
    }


    get down_total_bytes(){
        return this._down_total_bytes;
    }

    get up_speed(){
        return this._up_speed;
    }

    get down_speed(){
        return this._down_speed;
    }

}
H_ajax_sender.STATE_NOTHING = 0;
H_ajax_sender.STATE_QUEUED = 1;
H_ajax_sender.STATE_UPLOADING = 2;
H_ajax_sender.STATE_DOWNLOADING = 3;
h.libs.ajax_sender = H_ajax_sender;
window.H_ajax_sender = H_ajax_sender;
/**
 * @class H_ajax_file
 * @classdesc
 * Handles chunked file uploads via AJAX, including progress tracking, adaptive chunk sizing,
 * error handling, pause/resume, and merging chunks on the server.
 * @param {Array} fileLst - List of files to upload.
 * @param {H_ajax_sender} original_sender - The original AJAX sender.
 */
class H_ajax_file{
    constructor(fileLst, original_sender){
        this.debug = false;
        
        if (this.debug){
            console.log('new H_ajax_file','fileLst',fileLst,'original_request',original_request);
        }
        
        this.slices_total = 0; // count the total amount of slice sent
        
        // current start and end byte
        this.chunk_start = 0;
        this.chunk_end;
        // index of current chunk 
        this.chunk_index = 0;
        // adaptative size of chunk, depending the upload speed
        this.chunk_size = H_constants.slice_upload_size;
        
        // when there is a file in a form or in a request,
        // the request stop and send the file
        // once is done, re-send the original request
        this.original_sender = original_sender;
        this.original_time = (this.original_sender._data.has('time')) ? this.original_sender._data.get('time') : false;
        
        this.queue;
        this.file;
        
        // var Dom_ID = H_generics.get_unique_id();
        
        // handle stop of an upload
        this.aborted = false;
        // handle pause of an upload
        this.paused = false;
        
        // calculate the number of slices (chunk)
        // var startTime = Date.now();
        this.last_chunk_sending_time = 0; // enregistre le dernier temps passé à envoyer un chunk
        this.chunk_start_time = Date.now();
        
        this.xhr = new XMLHttpRequest();
        
        // progress bytes by chunk
        this.last_progress_time = 0;
        
        // progress for each chunk
        this.chunk_total_bytes = 0;        // chunk size
        this.chunk_uploaded_bytes = 0;     // already loaded 
        this.chunk_progress = 0;          // progress, 0 to 1
        
        this.errors = [];
        
        this.speed,this.file_count,this.file_sended;
        
        // all the file, independant of the sender widget 
        this.all = {
            'progress': 0,
            'total': 0,
            'loaded': 0
        };
        // if from a widget sender, compute the progress for this sender
        this.widget_sender = {
            'dom_id': false,
            'progress': 0,
            'total': 0,
            'loaded': 0
        };
        // current file
        this.current = {
            'name': '',
            'progress': 0,
            'total': 0,
            'loaded': 0,
            'small': false,
            'from_widget' : false
        };
        
        // for tracking time, used for this.debug
        // var startTime,endTime;
        
        this.uniqueid = Date.now();

        this.init(fileLst);
    }
    /**
     * Sends the next file chunk.
     * @returns {boolean} False if not sent.
     */
    send_chunk(){
        if (this.xhr.readyState > 0){
            console.log('not sending next chunk, xhr not ready');
            return false;
        }
        if (this.paused){
            console.log('not sending next chunk, upload paused');
            return false;
        }
        if (this.aborted){
            console.log('not sending next chunk, upload aborted');
            return false;
        }
        
        let chunk;
        if (!this.current.small){
            
            this.slices_total++; // count total slice for merge
            
            this.chunk_end = this.chunk_start + this.chunk_size;
            if(this.chunk_end > this.file.data.size) {
                // Pour que le dernier chunk soit correct
                this.chunk_end = this.file.data.size;
                this.chunk_size = this.chunk_end - this.chunk_start;
            }
        
            chunk = this.file.data.slice(this.chunk_start, this.chunk_end);
        }
        
        this.xhr.open('POST', H_constants.base_url + 'public/core/upload.php' , true);
        
        this.xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
        this.xhr.setRequestHeader('Cache-Control', 'no-cache');
        
        let formData = new FormData();
        formData.append('filename', this.file.data.name);
        formData.append('uniqueid', this.uniqueid);
        if (this.current.small){
            formData.append('filesize', this.file.data.size);
            formData.append('file', this.file.data, this.file.data.name + '!h!e!l!P!H!P!' + this.uniqueid);
            // formData.append('file', file, file.name);
            formData.append('full', 1);
            let last = this.file_count == (this.file_sended + 1);
            if (last) formData.append('last', 1);
        } else {
            formData.append('filesize', chunk.size);
            formData.append('chunk_index', this.chunk_index);
            formData.append('file', chunk, this.file.data.name);
        }
        if (this.original_time) formData.append('time', this.original_time);
        
        this.xhr.onload = this.on_load_chunk.bind(this);
        this.xhr.onerror = (evt) => {
            this.cancel_file(this.original_sender._current_error_callback);
        };
        this.xhr.upload.onprogress = this.on_progress_chunk.bind(this);
        
        this.xhr.send(formData);
    }
    /**
     * Handles the load event for a chunk upload.
     * @param {Event} evt - The event object.
     */
    on_load_chunk(evt){
        let result = this.xhr.responseText;
        let sendNextChunk = true;
        // console.log(result);
        if (result != 'ok'){
            if (!this.current.small){
                this.errors.push({'path': this.file.data.name,'chunk': this.chunk_index});
            } else {
                this.errors.push({'path': this.file.data.name,'chunk': false});
            }

            H_ui.message_popup(H_constants.get_text('upload_error_filename'));

            this.cancel_file(this.original_sender._current_error_callback);
            return;
        }
        
        this.xhr.abort();
        
        // add this chunk to loaded
        if (!this.current.small){
            this.current.loaded += this.chunk_size;
            this.all.loaded += this.chunk_size;
            if (this.current.from_widget) this.widget_sender.loaded += this.chunk_size;
        } else {
            this.current.loaded = this.file.data.size;
            this.all.loaded += this.file.data.size;
            if (this.current.from_widget) this.widget_sender.loaded += this.chunk_size;
        }
        
        this.chunk_uploaded_bytes = 0;
        
        // what to do next, sending next chunk or sending merge request ?
        if (this.current.small){
            this.file_sended++;
            this.process_queue();
            return;
        }
        
        if (sendNextChunk){
            if (this.chunk_end < this.file.data.size){
                // there is still some byte to send, prepare next chunk
                
                // ADAPTATIVE CHUNK
                // calcul le temps passé à envoyer le chunk
                let currentTime = Date.now();
                let chunkSendingTime = currentTime - this.chunk_start_time;
                // c'est le premier chunk que l'on envoie
                // Taille courante du chunk * le temps que l'on veut pour envoyer un chunk (ici 5s) / le temps passé a envoyé
                this.chunk_size = Math.round(this.chunk_size * ( 5000 / chunkSendingTime)); 
                // enregistre le dernier temps pour le prochain passage
                this.last_chunk_sending_time = chunkSendingTime;
                this.chunk_start_time = currentTime;
                
                this.chunk_index++;
                this.chunk_start = this.chunk_end;
                
                if (this.debug){
                    console.log('time sending chunk (s)', (this.last_chunk_sending_time/1000));
                }
                
                this.send_chunk();
            } else {
                // every byte have been sent, send merge request to the server
                
                // display the real time for uploading the file
                //~ let endChunkTime = Date.now();
                //~ let diff = (endChunkTime - startTime) / 1000;
                //~ console.log('time passed sending all chunk (s)', diff);
                
                this.merge_file();
            }
        } else {
            this.file_sended++;
            this.process_queue();
        }
    }
    /**
     * Handles progress events for a chunk upload.
     * @param {ProgressEvent} evt - The progress event.
     */
    on_progress_chunk(evt){
        // console.log(evt);
        //~ if(this.last_progress_time > 0 && evt.loaded != evt.total){
        if(this.last_progress_time > 0){
            let time_offset = Date.now() - this.last_progress_time;
            let bytes_offset = evt.loaded - this.chunk_uploaded_bytes;

            this.speed = Math.round(bytes_offset * (1000 / time_offset)); // byte par seconde
        }
        this.last_progress_time = Date.now();
        this.chunk_uploaded_bytes = evt.loaded;

        if (evt.lengthComputable) {
            this.chunk_progress = evt.loaded / evt.total;
            this.chunk_total_bytes = evt.total;
            
            //~ console.log('speed byte/s',up_speed);
            
            this.compute_progresss();
            // console.log(original_request);
            if(H_generics.is_function(this.original_sender._current_up_progress_callback)){
                this.original_sender._current_up_progress_callback(evt,this);
            } else if (this.original_sender.data.has('media_dom_id' + this.file.dom_id)) {
                // file uploaded with media uploader, send to it the progress upload
                // Media.lst[this.original_sender.data.get('media_dom_id' + this.file.dom_id)].upload_progress(evt,this);
                h.modules.media_a[this.original_sender.data.get('media_dom_id' + this.file.dom_id)].upload_progress(evt,this);
            }
        }else{
            this.chunk_progress = null;
            this.chunk_total_bytes = null;
        }
    }
    /**
     * Computes progress for the current file and all files.
     */
    compute_progresss(){
        let currentLoaded = this.current.loaded + this.chunk_uploaded_bytes;
        this.current.progress = currentLoaded / this.current.total;
        this.current.progress = this.current.progress > 1 ? 1 : this.current.progress;
        
        //~ console.log('current', this.current.progress);
        
        let allLoaded = this.all.loaded + this.chunk_uploaded_bytes;
        this.all.progress = allLoaded / this.all.total;
        this.all.progress = this.all.progress > 1 ? 1 : this.all.progress;
        
        // compute progress for the current widget sender 
        if (this.current.from_widget) {
            this.widget_sender.progress = allLoaded / this.all.total;
            this.widget_sender.progress = this.all.progress > 1 ? 1 : this.all.progress;
        }
    }
    /**
     * Sends a merge request to the server after all chunks are uploaded.
     */
    merge_file(){
        let settings = {};
        settings.url = H_constants.base_url + 'public/core/upload.php';
        settings.no_timer = true;
        settings.data = {
            'merge': 1,
            'name': this.file.data.name,
            'type': this.file.data.type,
            'size': this.file.data.size,
            'index': this.slices_total,
            'uniqueid': this.uniqueid
        };
        let last = this.file_count == (this.file_sended + 1);
        if (last) settings.data.last = 1;
        if (this.original_time) settings.data.time = this.original_time;

        settings.up_progress = false;
        settings.success = (res) => {
            // file send successfully
            this.file_sended++;
            this.process_queue();
        };
        if (this.debug){
            console.log('H_ajax_file sending merge request');
        }
        h.a.send(settings);
    }
    /**
     * Cancels the current file upload and notifies the server.
     * @param {Function} callback - Callback to execute after cancellation.
     */
    cancel_file(callback){
        this.aborted = true;
        // stop current xhr sending
        this.xhr.abort();
        
        // send a request to delete sent chunk
        let settings = {};
        settings.url = H_constants.base_url + 'public/core/upload.php';
        settings.no_timer = true;
        settings.data = {
            'cancel': 1,
            'name': this.file.data.name,
            'uniqueid': this.uniqueid
        };
        if (this.original_time) settings.data.time = this.original_time;
        settings.success = callback;
        h.a.send(settings);
    }
    /**
     * Pauses the current file upload.
     */
    pause_file(){
        this.paused = true;
    }
    /**
     * Resumes a paused file upload.
     */
    unpause_file(){
        this.paused = false;
        
        this.send_chunk();
    }
    /**
     * Processes the upload queue, sending the next file or finishing.
     */
    process_queue(){
        // check the "file" variable, if not empty, mean that a file have been uploaded, add it to the quota used/remain H_constants variable
        if (this.file){
            h_storage.left -= this.file.data.size;
            h_storage.usage += this.file.data.size;
            h_storage.percentage = (h_storage.usage / h_storage.quota) * 100;
        }
        if (this.queue.length > 0){
            
            // begin by the first element of the list to preserve the index with the file_path list (when uploading a folder in filemanager)
            this.file = this.queue.shift();
            if (this.file.dom_id){
                // initialize the progress for the widget sender
                if (this.widget_sender.dom_id != this.file.dom_id){
                    if (this.widget_sender.dom_id !== false) {
                        // if there was an other widget sender, send the end to it
                        if (this.original_sender._data.has('media_dom_id' + this.file.dom_id)) {
                            // Media.lst[this.widget_sender.dom_id].upload_end();
                            h.modules.media_a[this.widget_sender.dom_id].upload_end();
                        }
                    }
                    this.widget_sender.dom_id = this.file.dom_id;
                    this.widget_sender.progress = 0;
                    this.widget_sender.loaded = 0;
                    this.widget_sender.total = this.file.data.size;
                    this.queue.forEach( waiting_file => {
                        if (waiting_file.dom_id == this.file.dom_id) this.widget_sender.total += waiting_file.data.size;
                    });
                }
                this.current.from_widget = true;
            } else {
                this.current.from_widget = false;
            }
            
            this.current.total = this.file.data.size;
            this.current.small = (this.file.data.size <= H_constants.file_upload_size);
            
            this.current.loaded = 0;
            this.slices_total = 0;
            this.chunk_start = 0;
            this.chunk_index = 0;
            
            // can't use webkitRelativePath because it's not supported everywhere
            let filename = this.file.data.name;
            // comment below because don't see what's for
            // if (this.original_sender._data.has('file_path[]')){
                // let paths = this.original_sender._data.getAll('file_path[]');
                // filename = paths[this.file_sended] + file.data.name;
            // }
            
            this.current.name = filename;
            this.original_sender._data.append('lstFilePath[]', filename + '!h!e!l!P!H!P!' + this.uniqueid);
            // original_request.data.append('lstFilePath[]', filename);
            
            // send the first chunk
            this.send_chunk();
            
        } else {
            if (this.errors) this.original_sender._data.append('upload_errors', this.errors);
            // comment below because don't see what's for
            // if (this.original_sender._data.has('file_path[]')) this.original_sender._data.delete('file_path[]');
            if (this.original_sender._data.has('media_dom_id' + this.file.dom_id)) {
                // file uploaded with media uploader, send to it the progress upload
                // Media.lst[this.file.dom_id].upload_end();
                h.modules.media_a[this.file.dom_id].upload_end();
            }
            this.original_sender.send();
            
        }
    }
    /**
     * Initializes the upload queue and progress tracking.<br>
     * <br>
     * parse fileLst and put in this.queue for each dom_id found in it.<br>
     * A dom_id correspond to an uploader widget.<br>
     * File is an object with data, the FIleobject from the navigator and dom_id to retrieve the uploader widget<br>
     * dom_id can be false or a string. <br>
     * if false can't do the upload progress (can't retrieve the sender)<br>
     * when using the uploader widget from media it should always be the string reference to the widget
     * otherwise it's a custom send and you should use the upload callback of the ajax sender<br>
     * 
     * @param {Array} fileLst - List of files to upload.
     */
    init(fileLst){

        this.queue = fileLst;

        
        // total
        this.file_count = fileLst.length;
        this.file_sended = 0;
        
        let first_file = false;
        this.queue.forEach( (file) => {
            if (!first_file) first_file = file;
            this.all.total += file.data.size;
        });
        
        if (h_storage.left <= this.all.total) {
            H_ui.message_popup(H_constants.get_text('too_heavy_files', [this.all.total,h_storage.left]));
            return false;
        }

        if (this.original_sender._data.has('media_dom_id' + first_file.dom_id)){
            h.modules.media_a[this.original_sender.data.get('media_dom_id' + first_file.dom_id)].upload_start();
        }
        
        this.process_queue();
    }
}
/**
 * create link to global h.libs object
 */
h.libs.ajax_file = H_ajax_file;
window.H_ajax_file = H_ajax_file;
