<?php
$tl_data = array(
    'en'=>array (
        'module_name' => 'Deco',
        'deco-data-name' => 'Internal Name:',
        'confirm_delete' => 'delete',
        'title' => 'Edit Decorations',
        'copy' => 'Copy',
        'paste' => 'Paste',
        'select_deco' => 'Load:',
        'new_deco' => 'Create a new decor',
        'save' => 'Save',
        'deco-data-content' => 'Content:',
        'link'=>'Link',
        'info_link'=>'If set, the link will be set around the whole deco when you display it',
        'Aucune' => 'None',
        'scroll_fade_in' => 'Fade in when scroll',
        'scroll_smooth_scale' => 'Smoth scale when scroll',
        'click_fade_in' => 'Fade in when click',
        'apparition' => 'Appearing',
        'zoom_in' => 'Zoom in',
        'zoom_out' => 'Zoom out',
        'arrive_par_la_gauche' => 'coming from left',
        'arrive_par_la_droite' => 'Coming from right',
        'arrive_par_le_haut' => 'Coming from top',
        'arrive_par_le_bas' => 'Coming from bottom',
        'appear_up-250' => 'Appearing with 250 px move',
        'appear_up-500' => 'Appearing with 500 px move',
        'appear_up-750' => 'Appearing with 750 px move',
        'appear_up-1000' => 'Appearing with 1000 px move',
        'rotation_horaire' => 'Clock rotation',
        'rotation_anti-horaire' => 'Anticlock rotation',
        'pouls' => 'Pulsating',
        'select_block' => 'Block',
        'select_animation' => 'Animation',
    )
);