<?php
$tl_data = array(
    'fr'=>array (
        'module_name' => 'Deco',
        'deco-data-name' => 'Nom interne :',
        'confirm_delete' => 'supprimer',
        'title' => 'Editer les décorations',
        'copy' => 'Copier',
        'paste' => 'Coller',
        'select_deco' => 'Charger :',
        'new_deco' => 'Créer une nouvelle déco',
        'save' => 'Sauvegarder',
        'deco-data-content' => 'Contenu :',
        'link'=>'Lien',
        'info_link'=>'Si remplie, un lien sera ajouté tout autour de la déco',
        'Aucune' => 'Aucune',
        'scroll_fade_in' => 'Fondu entrant quand scroll',
        'scroll_smooth_scale' => 'Agrandissement doux quand scroll',
        'click_fade_in' => 'Fondu si click',
        'apparition' => 'Apparition',
        'zoom_in' => 'Zoom in',
        'zoom_out' => 'Zoom out',
        'arrive_par_la_gauche' => 'Arrive par la gauche',
        'arrive_par_la_droite' => 'Arrive par la droite',
        'arrive_par_le_haut' => 'Arrive par le haut',
        'arrive_par_le_bas' => 'Arrive par le bas',
        'appear_up-250' => 'Appartion avec mouvement de 250 px',
        'appear_up-500' => 'Appartion avec mouvement de 500 px',
        'appear_up-750' => 'Appartion avec mouvement de 750 px',
        'appear_up-1000' => 'Appartion avec mouvement de 1000 px',
        'rotation_horaire' => 'Rotation horaire',
        'rotation_anti-horaire' => 'Rotation anti-horaire',
        'pouls' => 'Pulsation',
        'select_block' => 'Block',
        'select_animation' => 'Animation',
    )
);